### ISSUE TITLE
error with scopus file build

### ISSUE THREAD

**Issue by risserlin** [BaderLab/SocialNetworkApp#100]
build incites network with the incites file in:
https://www.dropbox.com/s/0b7fj8kn4b036rr/Pawson_incites.xlsx?dl=0

then try and build a scopus network with:
https://www.dropbox.com/s/z430hqc2tywcxbd/Pawson_scopus.csv?dl=0

get the following stack:
java.lang.NullPointerException
        at org.baderlab.csapps.socialnetwork.model.academia.Scopus.parseScopusPu
bList(Scopus.java:196)
        at org.baderlab.csapps.socialnetwork.model.academia.Scopus.<init>(Scopus
.java:129)
        at org.baderlab.csapps.socialnetwork.tasks.ParseScopusCSVTask.run(ParseS
copusCSVTask.java:54)
        at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.inne
rRun(JDialogTaskManager.java:321)
        at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(
JDialogTaskManager.java:350)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by kofiav** [comment]
Unable to reproduce error in build 2cf10db7118fffa0149e255e06cd2053805865d8
