### ISSUE TITLE
Try to build second pubmed network and get null pointer

### ISSUE THREAD

**Issue by risserlin** [BaderLab/SocialNetworkApp#49]
build one network with pubmed xml file
works
try and build a second network from pubmed xml and get the following stack with Loading Netowrk view error:
java.lang.NullPointerException
	at org.baderlab.csapps.socialnetwork.tasks.CreateNetworkTask.run(CreateNetworkTask.java:331)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:321)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:350)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by risserlin** [comment]
not related to the second network.  Doesn't work with the file. 
https://www.dropbox.com/s/deay81tbi0yb197/pubmed_ADC_20052009.xml?dl=0

**Comment by risserlin** [comment]
there was an issue with the file returned by pubmed.  Recreated the file and it worked.  But probably better if there is a check and an error message comes up instead of crashing.

**Comment by kofiav** [comment]
I suspect that the NullPointerException is not at all related to the failed PubMed file. It almost always appears whenever I build networks and I haven't investigated it so far because it is relatively harmless (it does not prevent networks from loading). I have a hunch that it is being caused by concurrency issues.
