### ISSUE TITLE
Visual style not showing up in the style panel

### ISSUE THREAD

**Issue by risserlin** [BaderLab/SocialNetworkApp#65]
Although the network has a visual style the mapping info is not showing up in the style panel so you can tweak the style. (on windows 7)

**Comment by risserlin** [comment]
happens for an incite file.

Stack trace:
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at java.util.TreeMap.put(TreeMap.java:556)
        at java.util.TreeSet.add(TreeSet.java:255)
        at org.cytoscape.view.vizmap.gui.internal.view.VizMapPropertyBuilder.cre
ateMappingProperties(VizMapPropertyBuilder.java:258)
        at org.cytoscape.view.vizmap.gui.internal.view.VizMapPropertyBuilder.bui
ldProperty(VizMapPropertyBuilder.java:192)
        at org.cytoscape.view.vizmap.gui.internal.view.VisualPropertySheetItem.g
etPropSheetPnl(VisualPropertySheetItem.java:511)
        at org.cytoscape.view.vizmap.gui.internal.view.VisualPropertySheetItem.g
etMappingPnl(VisualPropertySheetItem.java:471)
        at org.cytoscape.view.vizmap.gui.internal.view.VisualPropertySheetItem.g
etMappingBtn(VisualPropertySheetItem.java:617)
        at org.cytoscape.view.vizmap.gui.internal.view.VisualPropertySheetItem.g
etTopPnl(VisualPropertySheetItem.java:436)
        at org.cytoscape.view.vizmap.gui.internal.view.VisualPropertySheetItem.i
nit(VisualPropertySheetItem.java:378)
        at org.cytoscape.view.vizmap.gui.internal.view.VisualPropertySheetItem.<
init>(VisualPropertySheetItem.java:149)
        at org.cytoscape.view.vizmap.gui.internal.view.VizMapperMediator.createV
isualPropertySheetItems(VizMapperMediator.java:920)
        at org.cytoscape.view.vizmap.gui.internal.view.VizMapperMediator.access$
2500(VizMapperMediator.java:121)
        at org.cytoscape.view.vizmap.gui.internal.view.VizMapperMediator$22.run(
VizMapperMediator.java:839)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
        at java.awt.EventQueue.access$200(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:694)
        at java.awt.EventQueue$3.run(EventQueue.java:692)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDo
main.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThre
ad.java:242)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.
java:161)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.
java:154)
        at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:182)
        at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:221)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:219)
        at java.awt.Dialog.show(Dialog.java:1082)
        at java.awt.Component.show(Component.java:1655)
        at java.awt.Component.setVisible(Component.java:1607)
        at java.awt.Window.setVisible(Window.java:1014)
        at java.awt.Dialog.setVisible(Dialog.java:1005)
        at org.cytoscape.work.internal.task.SwingTaskMonitor.open(SwingTaskMonit
or.java:153)
        at org.cytoscape.work.internal.task.JDialogTaskManager$2$1.run(JDialogTa
skManager.java:265)

**Comment by risserlin** [comment]
If you save the session and restore the session the incites visual style is then there.

**Comment by kofiav** [comment]
Very strange. I've been unable to duplicate this (on Windows 8). Does this happen with every InCites file?
