### ISSUE TITLE
When I try to build second network I get null pointer

### ISSUE THREAD

**Issue by risserlin** [BaderLab/SocialNetworkApp#94]
java.lang.NullPointerException
	at org.baderlab.csapps.socialnetwork.tasks.CreateNetworkTask.run(CreateNetworkTask.java:351)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:337)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:350)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by kofiav** [comment]
Is this still happening?

**Comment by kofiav** [comment]
Unable to reproduce bug.
